spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/bookstores
    username:
      root
    password:
      Sth@1234
  application:
    name: bookstore-backend-service
  jpa:
  hibernate:
  ddl-auto:
    none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
server:
  port: 0
