
spring:
  application:
    name: bookstore-ui-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

server:
  port: 0

api:
  url: http://localhost:9001/

payment:
  url: http://localhost:9002/

transport:
  url: http://localhost:9003/


