
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: backendService
          uri: lb://BOOKSTORE-BACKEND-SERVICE
          predicates:
            - Path=/api/**

        - id: uiService
          uri: lb://BOOKSTORE-UI-SERVICE
          predicates:
            - Path=/bookstore/**

        - id: paymentService
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: transportService
          uri: lb://TRANSPORTATION-SERVICE
          predicates:
            - Path=/transport/**

server:
  port: 8080
